### ISSUE TITLE
item list is not made into an rst list

### ISSUE THREAD

**Issue by wdpypere** [cuberat/Pod-POM-View-Restructured#4]
A proper rst list should be prefixed with `- `. eg:

```
- item 1
- item 2
```

However this is not the case.

Example pod:
```
=pod

=over

=item item1

=item item2

=back

=cut

```

output:
```
pod2rst --infile test.pod

item1



item2



```

**Comment by alexm** [comment]
Thanks for raising up this issue. Would you like to propose a test for this so we can check it's fixed and it won't regress later? I can guide you through the process if you need.

**Comment by wdpypere** [comment]
I have never done any perl code, let alone testing so I don't know if that is a good idea. :)  What would you expect as a test?

**Comment by alexm** [comment]
It should be pretty straight forward to add a new test file similar to [t/01convert.t](https://github.com/cuberat/Pod-POM-View-Restructured/blob/master/t/01convert.t) that checks that the output is OK for the example you wrote above.

If you'd like to learn how to do it, I can assist you. Otherwise, I'll take care of it, no problem. I'm just giving you the chance to try if you're interested :smile:

**Comment by wdpypere** [comment]
@alexm I made an attempt in #5

**Comment by alexm** [comment]
@wdpypere looks good to me. Nice job! :clap: 

I will try to fix it this weekend. Thanks a  lot.

**Comment by wdpypere** [comment]
@alexm I tested your fix on our code base and at first glance it seems to do exactly what I would expect it to do.

**Comment by alexm** [comment]
New release 1.000002 uploaded to CPAN, will be hopefully available soon in a mirror near you :wink:

**Comment by wdpypere** [comment]
@alexm thanks a lot!
